# screen
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# drawing
LINE_WIDTH = 2

# player
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 330
PLAYER_SPEED = 200

# asteroids
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
